(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=960){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
var notifyyt,notifyqueue;function onYouTubeIframeAPIReady(){notifyyt(),window.loadyt=function(e){e()}}window.loadyt=function(e){var t=document.createElement("script");t.src="https://www.youtube.com/player_api";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n),notifyqueue||(notifyqueue=[],notifyyt=function(){var e;for(e=0;e<notifyqueue.length;++e){(0,notifyqueue[e])()}}),notifyqueue.push(e)};window.plstp||(window.plstp=[]),plst=function(p,w){for(f in window.plstp)window.plstp[f]();window.plstp=[],window.plstp[p]=w},plrm=function(p){delete window.plstp[p]};ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=960){var a='data-src';var e=document.querySelector('.js1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/pic1-960.jpg');
var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pic2-1920.jpg':'images/pic2-960.jpg');
var a='data-src';var e=document.querySelector('.js3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pic3-1920.jpg':'images/pic3-960.jpg');
var a='data-src';var e=document.querySelector('.js4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pic4-1680.jpg':'images/pic4-840.jpg');}else{var a='data-src';var e=document.querySelector('.js1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pic1-640.jpg':'images/pic1-320.jpg');
var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pic2-640.jpg':'images/pic2-320.jpg');
var a='data-src';var e=document.querySelector('.js3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pic3-640.jpg':'images/pic3-320.jpg');
var a='data-src';var e=document.querySelector('.js4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pic4-560.jpg':'images/pic4-280.jpg');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
window.loadyt(function(){var p=new YT.Player('pl1',{host:'https://www.youtube-nocookie.com',videoId: 'TWyFQSFLakg',playerVars:{'playsinline':1,'rel':0},events:{onStateChange:function(e){1===e.data&&plst('pl1',function(){e.target.pauseVideo()}),2===e.data&&plrm('pl1')}}});});(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
ldsrcset('.js9 source');ldsrcset('.js10 source');ldsrcset('.js11 source');ldsrcset('.js12 source');if(location.hash){var o=location.hash.replace('#',''),e=function(){if(document.body.getBoundingClientRect().top>0){var t=document.querySelectorAll('[name="'+o+'"]')[0];t&&t.scrollIntoView(!0),setTimeout(e,100)}};e()}
});